/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Hostel IoT Management API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminUser,
  AuthResponse,
  ChillerUsageRecord,
  DashboardSummary,
  ErrorResponse,
  FilterControlBody,
  GetRoomPowerHistoryParams,
  GetSystemLogsParams,
  GetWaterChillerHistoryParams,
  GetWaterTankHistoryParams,
  HealthStatus,
  LightGroup,
  LightGroupUpdateBody,
  LightToggleBody,
  LoginBody,
  MotorControlBody,
  PowerAnomaly,
  PowerSummary,
  PowerUsageRecord,
  RoomPowerStat,
  SuccessResponse,
  SystemLog,
  TemperatureSetBody,
  WaterChillerStatus,
  WaterTankStatus,
  WaterUsageRecord,
} from "./api.schemas";

import { customFetch } from "@/lib/custom-fetch";
import type { ErrorType, BodyType } from "@/lib/custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Admin login
 */
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

export const login = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginBody>;
export type LoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Admin login
 */
export const useLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};

/**
 * @summary Logout
 */
export const getLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const logout = async (
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout
 */
export const useLogout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<AdminUser> => {
  return customFetch<AdminUser>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get overall system summary
 */
export const getGetDashboardSummaryUrl = () => {
  return `/api/dashboard/summary`;
};

export const getDashboardSummary = async (
  options?: RequestInit,
): Promise<DashboardSummary> => {
  return customFetch<DashboardSummary>(getGetDashboardSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDashboardSummaryQueryKey = () => {
  return [`/api/dashboard/summary`] as const;
};

export const getGetDashboardSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardSummary>>
  > = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDashboardSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardSummary>>
>;
export type GetDashboardSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Get overall system summary
 */

export function useGetDashboardSummary<
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current water tank status
 */
export const getGetWaterTankStatusUrl = () => {
  return `/api/water-tank/status`;
};

export const getWaterTankStatus = async (
  options?: RequestInit,
): Promise<WaterTankStatus> => {
  return customFetch<WaterTankStatus>(getGetWaterTankStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWaterTankStatusQueryKey = () => {
  return [`/api/water-tank/status`] as const;
};

export const getGetWaterTankStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getWaterTankStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWaterTankStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWaterTankStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWaterTankStatus>>
  > = ({ signal }) => getWaterTankStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWaterTankStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWaterTankStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWaterTankStatus>>
>;
export type GetWaterTankStatusQueryError = ErrorType<unknown>;

/**
 * @summary Get current water tank status
 */

export function useGetWaterTankStatus<
  TData = Awaited<ReturnType<typeof getWaterTankStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWaterTankStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWaterTankStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Manually control water motor
 */
export const getControlMotorUrl = () => {
  return `/api/water-tank/motor`;
};

export const controlMotor = async (
  motorControlBody: MotorControlBody,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getControlMotorUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(motorControlBody),
  });
};

export const getControlMotorMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof controlMotor>>,
    TError,
    { data: BodyType<MotorControlBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof controlMotor>>,
  TError,
  { data: BodyType<MotorControlBody> },
  TContext
> => {
  const mutationKey = ["controlMotor"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof controlMotor>>,
    { data: BodyType<MotorControlBody> }
  > = (props) => {
    const { data } = props ?? {};

    return controlMotor(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ControlMotorMutationResult = NonNullable<
  Awaited<ReturnType<typeof controlMotor>>
>;
export type ControlMotorMutationBody = BodyType<MotorControlBody>;
export type ControlMotorMutationError = ErrorType<unknown>;

/**
 * @summary Manually control water motor
 */
export const useControlMotor = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof controlMotor>>,
    TError,
    { data: BodyType<MotorControlBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof controlMotor>>,
  TError,
  { data: BodyType<MotorControlBody> },
  TContext
> => {
  return useMutation(getControlMotorMutationOptions(options));
};

/**
 * @summary Get water tank usage history
 */
export const getGetWaterTankHistoryUrl = (
  params?: GetWaterTankHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/water-tank/history?${stringifiedParams}`
    : `/api/water-tank/history`;
};

export const getWaterTankHistory = async (
  params?: GetWaterTankHistoryParams,
  options?: RequestInit,
): Promise<WaterUsageRecord[]> => {
  return customFetch<WaterUsageRecord[]>(getGetWaterTankHistoryUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetWaterTankHistoryQueryKey = (
  params?: GetWaterTankHistoryParams,
) => {
  return [`/api/water-tank/history`, ...(params ? [params] : [])] as const;
};

export const getGetWaterTankHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getWaterTankHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetWaterTankHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getWaterTankHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetWaterTankHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWaterTankHistory>>
  > = ({ signal }) =>
    getWaterTankHistory(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWaterTankHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWaterTankHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWaterTankHistory>>
>;
export type GetWaterTankHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get water tank usage history
 */

export function useGetWaterTankHistory<
  TData = Awaited<ReturnType<typeof getWaterTankHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetWaterTankHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getWaterTankHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWaterTankHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get water chiller status
 */
export const getGetWaterChillerStatusUrl = () => {
  return `/api/water-chiller/status`;
};

export const getWaterChillerStatus = async (
  options?: RequestInit,
): Promise<WaterChillerStatus> => {
  return customFetch<WaterChillerStatus>(getGetWaterChillerStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWaterChillerStatusQueryKey = () => {
  return [`/api/water-chiller/status`] as const;
};

export const getGetWaterChillerStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getWaterChillerStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWaterChillerStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWaterChillerStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWaterChillerStatus>>
  > = ({ signal }) => getWaterChillerStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWaterChillerStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWaterChillerStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWaterChillerStatus>>
>;
export type GetWaterChillerStatusQueryError = ErrorType<unknown>;

/**
 * @summary Get water chiller status
 */

export function useGetWaterChillerStatus<
  TData = Awaited<ReturnType<typeof getWaterChillerStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWaterChillerStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWaterChillerStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Set target temperature for chiller
 */
export const getSetChillerTemperatureUrl = () => {
  return `/api/water-chiller/temperature`;
};

export const setChillerTemperature = async (
  temperatureSetBody: TemperatureSetBody,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getSetChillerTemperatureUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(temperatureSetBody),
  });
};

export const getSetChillerTemperatureMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setChillerTemperature>>,
    TError,
    { data: BodyType<TemperatureSetBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setChillerTemperature>>,
  TError,
  { data: BodyType<TemperatureSetBody> },
  TContext
> => {
  const mutationKey = ["setChillerTemperature"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setChillerTemperature>>,
    { data: BodyType<TemperatureSetBody> }
  > = (props) => {
    const { data } = props ?? {};

    return setChillerTemperature(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetChillerTemperatureMutationResult = NonNullable<
  Awaited<ReturnType<typeof setChillerTemperature>>
>;
export type SetChillerTemperatureMutationBody = BodyType<TemperatureSetBody>;
export type SetChillerTemperatureMutationError = ErrorType<unknown>;

/**
 * @summary Set target temperature for chiller
 */
export const useSetChillerTemperature = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setChillerTemperature>>,
    TError,
    { data: BodyType<TemperatureSetBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof setChillerTemperature>>,
  TError,
  { data: BodyType<TemperatureSetBody> },
  TContext
> => {
  return useMutation(getSetChillerTemperatureMutationOptions(options));
};

/**
 * @summary Manually control chiller filter
 */
export const getControlChillerFilterUrl = () => {
  return `/api/water-chiller/filter`;
};

export const controlChillerFilter = async (
  filterControlBody: FilterControlBody,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getControlChillerFilterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(filterControlBody),
  });
};

export const getControlChillerFilterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof controlChillerFilter>>,
    TError,
    { data: BodyType<FilterControlBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof controlChillerFilter>>,
  TError,
  { data: BodyType<FilterControlBody> },
  TContext
> => {
  const mutationKey = ["controlChillerFilter"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof controlChillerFilter>>,
    { data: BodyType<FilterControlBody> }
  > = (props) => {
    const { data } = props ?? {};

    return controlChillerFilter(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ControlChillerFilterMutationResult = NonNullable<
  Awaited<ReturnType<typeof controlChillerFilter>>
>;
export type ControlChillerFilterMutationBody = BodyType<FilterControlBody>;
export type ControlChillerFilterMutationError = ErrorType<unknown>;

/**
 * @summary Manually control chiller filter
 */
export const useControlChillerFilter = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof controlChillerFilter>>,
    TError,
    { data: BodyType<FilterControlBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof controlChillerFilter>>,
  TError,
  { data: BodyType<FilterControlBody> },
  TContext
> => {
  return useMutation(getControlChillerFilterMutationOptions(options));
};

/**
 * @summary Get chiller usage history
 */
export const getGetWaterChillerHistoryUrl = (
  params?: GetWaterChillerHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/water-chiller/history?${stringifiedParams}`
    : `/api/water-chiller/history`;
};

export const getWaterChillerHistory = async (
  params?: GetWaterChillerHistoryParams,
  options?: RequestInit,
): Promise<ChillerUsageRecord[]> => {
  return customFetch<ChillerUsageRecord[]>(
    getGetWaterChillerHistoryUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetWaterChillerHistoryQueryKey = (
  params?: GetWaterChillerHistoryParams,
) => {
  return [`/api/water-chiller/history`, ...(params ? [params] : [])] as const;
};

export const getGetWaterChillerHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getWaterChillerHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetWaterChillerHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getWaterChillerHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetWaterChillerHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWaterChillerHistory>>
  > = ({ signal }) =>
    getWaterChillerHistory(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWaterChillerHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWaterChillerHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWaterChillerHistory>>
>;
export type GetWaterChillerHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get chiller usage history
 */

export function useGetWaterChillerHistory<
  TData = Awaited<ReturnType<typeof getWaterChillerHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetWaterChillerHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getWaterChillerHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWaterChillerHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all light groups and their status
 */
export const getGetLightGroupsUrl = () => {
  return `/api/lights/groups`;
};

export const getLightGroups = async (
  options?: RequestInit,
): Promise<LightGroup[]> => {
  return customFetch<LightGroup[]>(getGetLightGroupsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLightGroupsQueryKey = () => {
  return [`/api/lights/groups`] as const;
};

export const getGetLightGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getLightGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLightGroups>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLightGroupsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLightGroups>>> = ({
    signal,
  }) => getLightGroups({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLightGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLightGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLightGroups>>
>;
export type GetLightGroupsQueryError = ErrorType<unknown>;

/**
 * @summary Get all light groups and their status
 */

export function useGetLightGroups<
  TData = Awaited<ReturnType<typeof getLightGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLightGroups>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLightGroupsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a light group schedule or status
 */
export const getUpdateLightGroupUrl = (groupId: string) => {
  return `/api/lights/groups/${groupId}`;
};

export const updateLightGroup = async (
  groupId: string,
  lightGroupUpdateBody: LightGroupUpdateBody,
  options?: RequestInit,
): Promise<LightGroup> => {
  return customFetch<LightGroup>(getUpdateLightGroupUrl(groupId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(lightGroupUpdateBody),
  });
};

export const getUpdateLightGroupMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLightGroup>>,
    TError,
    { groupId: string; data: BodyType<LightGroupUpdateBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLightGroup>>,
  TError,
  { groupId: string; data: BodyType<LightGroupUpdateBody> },
  TContext
> => {
  const mutationKey = ["updateLightGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLightGroup>>,
    { groupId: string; data: BodyType<LightGroupUpdateBody> }
  > = (props) => {
    const { groupId, data } = props ?? {};

    return updateLightGroup(groupId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLightGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLightGroup>>
>;
export type UpdateLightGroupMutationBody = BodyType<LightGroupUpdateBody>;
export type UpdateLightGroupMutationError = ErrorType<unknown>;

/**
 * @summary Update a light group schedule or status
 */
export const useUpdateLightGroup = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLightGroup>>,
    TError,
    { groupId: string; data: BodyType<LightGroupUpdateBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateLightGroup>>,
  TError,
  { groupId: string; data: BodyType<LightGroupUpdateBody> },
  TContext
> => {
  return useMutation(getUpdateLightGroupMutationOptions(options));
};

/**
 * @summary Manually toggle a light group on/off
 */
export const getToggleLightGroupUrl = (groupId: string) => {
  return `/api/lights/groups/${groupId}/toggle`;
};

export const toggleLightGroup = async (
  groupId: string,
  lightToggleBody: LightToggleBody,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getToggleLightGroupUrl(groupId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(lightToggleBody),
  });
};

export const getToggleLightGroupMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleLightGroup>>,
    TError,
    { groupId: string; data: BodyType<LightToggleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toggleLightGroup>>,
  TError,
  { groupId: string; data: BodyType<LightToggleBody> },
  TContext
> => {
  const mutationKey = ["toggleLightGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toggleLightGroup>>,
    { groupId: string; data: BodyType<LightToggleBody> }
  > = (props) => {
    const { groupId, data } = props ?? {};

    return toggleLightGroup(groupId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToggleLightGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof toggleLightGroup>>
>;
export type ToggleLightGroupMutationBody = BodyType<LightToggleBody>;
export type ToggleLightGroupMutationError = ErrorType<unknown>;

/**
 * @summary Manually toggle a light group on/off
 */
export const useToggleLightGroup = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleLightGroup>>,
    TError,
    { groupId: string; data: BodyType<LightToggleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof toggleLightGroup>>,
  TError,
  { groupId: string; data: BodyType<LightToggleBody> },
  TContext
> => {
  return useMutation(getToggleLightGroupMutationOptions(options));
};

/**
 * @summary Get power consumption per room
 */
export const getGetRoomPowerStatsUrl = () => {
  return `/api/power/rooms`;
};

export const getRoomPowerStats = async (
  options?: RequestInit,
): Promise<RoomPowerStat[]> => {
  return customFetch<RoomPowerStat[]>(getGetRoomPowerStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRoomPowerStatsQueryKey = () => {
  return [`/api/power/rooms`] as const;
};

export const getGetRoomPowerStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoomPowerStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRoomPowerStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRoomPowerStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRoomPowerStats>>
  > = ({ signal }) => getRoomPowerStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoomPowerStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRoomPowerStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoomPowerStats>>
>;
export type GetRoomPowerStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get power consumption per room
 */

export function useGetRoomPowerStats<
  TData = Awaited<ReturnType<typeof getRoomPowerStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRoomPowerStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRoomPowerStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get power history for a specific room
 */
export const getGetRoomPowerHistoryUrl = (
  roomId: string,
  params?: GetRoomPowerHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/power/rooms/${roomId}/history?${stringifiedParams}`
    : `/api/power/rooms/${roomId}/history`;
};

export const getRoomPowerHistory = async (
  roomId: string,
  params?: GetRoomPowerHistoryParams,
  options?: RequestInit,
): Promise<PowerUsageRecord[]> => {
  return customFetch<PowerUsageRecord[]>(
    getGetRoomPowerHistoryUrl(roomId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetRoomPowerHistoryQueryKey = (
  roomId: string,
  params?: GetRoomPowerHistoryParams,
) => {
  return [
    `/api/power/rooms/${roomId}/history`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetRoomPowerHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoomPowerHistory>>,
  TError = ErrorType<unknown>,
>(
  roomId: string,
  params?: GetRoomPowerHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getRoomPowerHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRoomPowerHistoryQueryKey(roomId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRoomPowerHistory>>
  > = ({ signal }) =>
    getRoomPowerHistory(roomId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!roomId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoomPowerHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRoomPowerHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoomPowerHistory>>
>;
export type GetRoomPowerHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get power history for a specific room
 */

export function useGetRoomPowerHistory<
  TData = Awaited<ReturnType<typeof getRoomPowerHistory>>,
  TError = ErrorType<unknown>,
>(
  roomId: string,
  params?: GetRoomPowerHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getRoomPowerHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRoomPowerHistoryQueryOptions(
    roomId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get power anomaly alerts (e.g. holiday usage)
 */
export const getGetPowerAnomaliesUrl = () => {
  return `/api/power/anomalies`;
};

export const getPowerAnomalies = async (
  options?: RequestInit,
): Promise<PowerAnomaly[]> => {
  return customFetch<PowerAnomaly[]>(getGetPowerAnomaliesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPowerAnomaliesQueryKey = () => {
  return [`/api/power/anomalies`] as const;
};

export const getGetPowerAnomaliesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPowerAnomalies>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPowerAnomalies>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPowerAnomaliesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPowerAnomalies>>
  > = ({ signal }) => getPowerAnomalies({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPowerAnomalies>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPowerAnomaliesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPowerAnomalies>>
>;
export type GetPowerAnomaliesQueryError = ErrorType<unknown>;

/**
 * @summary Get power anomaly alerts (e.g. holiday usage)
 */

export function useGetPowerAnomalies<
  TData = Awaited<ReturnType<typeof getPowerAnomalies>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPowerAnomalies>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPowerAnomaliesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get overall power consumption summary
 */
export const getGetPowerSummaryUrl = () => {
  return `/api/power/summary`;
};

export const getPowerSummary = async (
  options?: RequestInit,
): Promise<PowerSummary> => {
  return customFetch<PowerSummary>(getGetPowerSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPowerSummaryQueryKey = () => {
  return [`/api/power/summary`] as const;
};

export const getGetPowerSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getPowerSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPowerSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPowerSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPowerSummary>>> = ({
    signal,
  }) => getPowerSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPowerSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPowerSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPowerSummary>>
>;
export type GetPowerSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Get overall power consumption summary
 */

export function useGetPowerSummary<
  TData = Awaited<ReturnType<typeof getPowerSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPowerSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPowerSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get system event logs
 */
export const getGetSystemLogsUrl = (params?: GetSystemLogsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/logs?${stringifiedParams}`
    : `/api/logs`;
};

export const getSystemLogs = async (
  params?: GetSystemLogsParams,
  options?: RequestInit,
): Promise<SystemLog[]> => {
  return customFetch<SystemLog[]>(getGetSystemLogsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetSystemLogsQueryKey = (params?: GetSystemLogsParams) => {
  return [`/api/logs`, ...(params ? [params] : [])] as const;
};

export const getGetSystemLogsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSystemLogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSystemLogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSystemLogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSystemLogsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemLogs>>> = ({
    signal,
  }) => getSystemLogs(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSystemLogs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSystemLogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSystemLogs>>
>;
export type GetSystemLogsQueryError = ErrorType<unknown>;

/**
 * @summary Get system event logs
 */

export function useGetSystemLogs<
  TData = Awaited<ReturnType<typeof getSystemLogs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetSystemLogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSystemLogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSystemLogsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
