/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Hostel IoT Management API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
  message: string;
}

export interface LoginBody {
  email: string;
  password: string;
}

export interface AdminUser {
  id: string;
  email: string;
  name: string;
  role: string;
}

export interface AuthResponse {
  success: boolean;
  user: AdminUser;
}

export type DashboardSummaryWaterTank = {
  level: number;
  motorStatus: string;
  lastUpdated: string;
};

export type DashboardSummaryWaterChiller = {
  level: number;
  temperature: number;
  targetTemperature: number;
  filterStatus: string;
  coolerStatus: string;
  lastUpdated: string;
};

export type DashboardSummaryLights = {
  totalGroups: number;
  activeGroups: number;
  lastUpdated: string;
};

export type DashboardSummaryPower = {
  totalConsumptionKwh: number;
  activeRooms: number;
  anomalyCount: number;
  lastUpdated: string;
};

export type SystemLogModule =
  (typeof SystemLogModule)[keyof typeof SystemLogModule];

export const SystemLogModule = {
  "water-tank": "water-tank",
  "water-chiller": "water-chiller",
  lights: "lights",
  power: "power",
  auth: "auth",
  system: "system",
} as const;

export type SystemLogLevel =
  (typeof SystemLogLevel)[keyof typeof SystemLogLevel];

export const SystemLogLevel = {
  info: "info",
  warning: "warning",
  error: "error",
  critical: "critical",
} as const;

export type SystemLogDetails = { [key: string]: unknown };

export interface SystemLog {
  id: string;
  timestamp: string;
  module: SystemLogModule;
  level: SystemLogLevel;
  message: string;
  details?: SystemLogDetails;
}

export interface DashboardSummary {
  waterTank: DashboardSummaryWaterTank;
  waterChiller: DashboardSummaryWaterChiller;
  lights: DashboardSummaryLights;
  power: DashboardSummaryPower;
  recentAlerts: SystemLog[];
}

export type WaterTankStatusMotorStatus =
  (typeof WaterTankStatusMotorStatus)[keyof typeof WaterTankStatusMotorStatus];

export const WaterTankStatusMotorStatus = {
  on: "on",
  off: "off",
  auto: "auto",
} as const;

export type WaterTankStatusMotorMode =
  (typeof WaterTankStatusMotorMode)[keyof typeof WaterTankStatusMotorMode];

export const WaterTankStatusMotorMode = {
  manual: "manual",
  auto: "auto",
} as const;

export interface WaterTankStatus {
  levelPercent: number;
  motorStatus: WaterTankStatusMotorStatus;
  motorMode: WaterTankStatusMotorMode;
  warningTriggered: boolean;
  autoTriggered: boolean;
  capacityLiters: number;
  currentLiters: number;
  lastUpdated: string;
}

export type MotorControlBodyAction =
  (typeof MotorControlBodyAction)[keyof typeof MotorControlBodyAction];

export const MotorControlBodyAction = {
  on: "on",
  off: "off",
  auto: "auto",
} as const;

export interface MotorControlBody {
  action: MotorControlBodyAction;
}

export interface WaterUsageRecord {
  timestamp: string;
  levelPercent: number;
  litersUsed: number;
  motorStatus: string;
}

export type WaterChillerStatusFilterStatus =
  (typeof WaterChillerStatusFilterStatus)[keyof typeof WaterChillerStatusFilterStatus];

export const WaterChillerStatusFilterStatus = {
  on: "on",
  off: "off",
  auto: "auto",
} as const;

export type WaterChillerStatusFilterMode =
  (typeof WaterChillerStatusFilterMode)[keyof typeof WaterChillerStatusFilterMode];

export const WaterChillerStatusFilterMode = {
  manual: "manual",
  auto: "auto",
} as const;

export type WaterChillerStatusCoolerStatus =
  (typeof WaterChillerStatusCoolerStatus)[keyof typeof WaterChillerStatusCoolerStatus];

export const WaterChillerStatusCoolerStatus = {
  on: "on",
  off: "off",
} as const;

export interface WaterChillerStatus {
  levelPercent: number;
  temperature: number;
  targetTemperature: number;
  filterStatus: WaterChillerStatusFilterStatus;
  filterMode: WaterChillerStatusFilterMode;
  coolerStatus: WaterChillerStatusCoolerStatus;
  capacityLiters: number;
  currentLiters: number;
  lastUpdated: string;
}

export interface TemperatureSetBody {
  temperature: number;
}

export type FilterControlBodyAction =
  (typeof FilterControlBodyAction)[keyof typeof FilterControlBodyAction];

export const FilterControlBodyAction = {
  on: "on",
  off: "off",
  auto: "auto",
} as const;

export interface FilterControlBody {
  action: FilterControlBodyAction;
}

export interface ChillerUsageRecord {
  timestamp: string;
  levelPercent: number;
  temperature: number;
  litersUsed: number;
  filterStatus: string;
  coolerStatus: string;
}

export type LightGroupType =
  (typeof LightGroupType)[keyof typeof LightGroupType];

export const LightGroupType = {
  critical: "critical",
  common: "common",
  support: "support",
} as const;

export type LightGroupMode =
  (typeof LightGroupMode)[keyof typeof LightGroupMode];

export const LightGroupMode = {
  auto: "auto",
  manual: "manual",
  "always-on": "always-on",
} as const;

export interface LightSchedule {
  startTime: string;
  endTime: string;
  days: string[];
}

export interface LightGroup {
  id: string;
  name: string;
  type: LightGroupType;
  isOn: boolean;
  mode: LightGroupMode;
  schedules: LightSchedule[];
  lightCount: number;
  description: string;
  locations: string[];
  lastUpdated: string;
}

export type LightGroupUpdateBodyMode =
  (typeof LightGroupUpdateBodyMode)[keyof typeof LightGroupUpdateBodyMode];

export const LightGroupUpdateBodyMode = {
  auto: "auto",
  manual: "manual",
  "always-on": "always-on",
} as const;

export interface LightGroupUpdateBody {
  mode?: LightGroupUpdateBodyMode;
  schedules?: LightSchedule[];
}

export interface LightToggleBody {
  on: boolean;
}

export type RoomPowerStatOccupancyStatus =
  (typeof RoomPowerStatOccupancyStatus)[keyof typeof RoomPowerStatOccupancyStatus];

export const RoomPowerStatOccupancyStatus = {
  occupied: "occupied",
  vacant: "vacant",
  holiday: "holiday",
} as const;

export interface RoomPowerStat {
  roomId: string;
  roomName: string;
  floor: number;
  wing: string;
  currentWatts: number;
  todayKwh: number;
  monthKwh: number;
  isAnomaly: boolean;
  anomalyReason?: string;
  occupancyStatus: RoomPowerStatOccupancyStatus;
  lastUpdated: string;
}

export interface PowerUsageRecord {
  timestamp: string;
  watts: number;
  kwh: number;
}

export type PowerAnomalySeverity =
  (typeof PowerAnomalySeverity)[keyof typeof PowerAnomalySeverity];

export const PowerAnomalySeverity = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface PowerAnomaly {
  roomId: string;
  roomName: string;
  reason: string;
  currentWatts: number;
  detectedAt: string;
  severity: PowerAnomalySeverity;
}

export interface PowerSummary {
  totalRooms: number;
  occupiedRooms: number;
  totalCurrentWatts: number;
  todayTotalKwh: number;
  monthTotalKwh: number;
  anomalyRooms: number;
  peakUsageTime: string;
  averagePerRoom: number;
}

export type GetWaterTankHistoryParams = {
  hours?: number;
};

export type GetWaterChillerHistoryParams = {
  hours?: number;
};

export type GetRoomPowerHistoryParams = {
  hours?: number;
};

export type GetSystemLogsParams = {
  limit?: number;
  module?: GetSystemLogsModule;
};

export type GetSystemLogsModule =
  (typeof GetSystemLogsModule)[keyof typeof GetSystemLogsModule];

export const GetSystemLogsModule = {
  "water-tank": "water-tank",
  "water-chiller": "water-chiller",
  lights: "lights",
  power: "power",
  auth: "auth",
  system: "system",
} as const;
